language: node_js
node_js:
- '12.22.12'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=coopcycle)
  - secure: yKTk1Ijbu/qVXhiqJtelVheVMB206D1nVhBTPflYj2pkyOHCpLfj3oim8+d9ymJGhZ53cvnAPNtVQ6KRWlxvFpw7hA4QW5dEekIjpxgcTyDzESIDUPuo525P8DvQUQGLdqncOvfA3/+Ec2pBMdBOmkTotJzZIXFRz/DGPrlEWcQa86IMix0b/753stIcwrPLTQAs0RILschA9MNKVZuBpHAU9gdi0HzkOFjnykwLikpsZSbVsX2vMItozDfcVi2m0Fo/RXuApw5/T5X2e8JhCcV3IJYPDzUFje0+8UXPDipQDyZtr2HvC/bzYTImYVCCsbXBBogALdIrAh4yQOZSW35wYFDZIqkbcJLeIPe0bowMBlnRli8LWe+y7mqSA6Ms/zgYzv4trPMuxPgdQsKgHt/XywhbmBLk2QHKtpYFSb8HhL7GNvp1AR4d+eRh9AAlkmxRWj7Rn9Tx6LLom58XhvcydwUavfqMHJLYV0qPJt2HHSiWqvAS6pT3bJB7GtLk4nFCMtYbe+PWs0fxAp8SpEyPFxa3Wg7pJVmHeuLO1atdiTxUyxlimZbtxoPbPHFeoCoenuqBvyl8DQM32AaYgdKXjuUjnNclHJ2ZHYu4iqDCGVGnKHGHsvkVdjbtLP5xaCmhRcEVdb7R2OrPrzM+2nx7zxQoWB1bYKboZEs99eg=
  # MATTERMOST_HOOK_URL
  - secure: qtdy34Va4Zfl6S6ifrLDSHKjA6+u32l2ZbFAMyn+3ex2BwiJ4VD9mYignmA5THlf9Js1PDkRXnSAuhUZ4Z/xF2oTRmCTIW+UWyv36G/tFUBY30s6XGlvCOlcXK+DMgTtyRkvKW7V3+OY00RRLY0WB1hvHBv+ELX1ZJjuieBLbyqGadT/VCcOeDViuC9eHi7n85qjgwpsA3lcNaBZAQBrbqVLp/pW779gAYvE27T2LFt68Hrv4AHeuuMu/OVL5E0cWRnABVscdXEaj7XDZLaK7PvH2+WeCNXKXxLCe0V4A3bSTxo4ZbES5fpm6AM0TaAgWsuksYMCfZFnaQ3DohM+5P38C2o8wLGFsK7t8HuTWJbQ39anZ3SgAP1hWlZSEYIKZ20PzdMfshw2+YCOuF0n3z/aLdLgjAfemC+l1HtmONpxl2X7X9GWTc8JN80JAXXQdd8LVWcyehc4pAnOVZTItq4MkP2o7SCDwsJwB2KkUn+JmTVo5zow98gHY0EXA2EzbS6bnHAAd0gbzvkggScJItKqqhCQukxQzbBn8X2DrrfGw7xALz8NA+h6PyddU6aMDRq3WOf6/NJND8PtxJnz8Etr1mAv38O/jOqv5kXwNq9x6VqwynCLbY/ix1hHO1SQjcBD2tOgBrcWGOkpbabA+m4v8ruCj3Mdm8DaujCRm/g=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
